use_frameworks!

platform :ios, '8.0'

target 'TQCategotyKit_Example' do
  pod 'TQCategotyKit', :path => '../'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MBProgressHUD'

  target 'TQCategotyKit_Tests' do
    inherit! :search_paths

    
  end
end

